economico/urls.py
from django.conf.urls.defaults import *
from django.conf import settings
 
urlpatterns = patterns('economico.views',
                        (r'^$', 'index'),
                        (r'^economico/canasta-basica/$', 'canasta_basica'),
                        (r'^economico/canasta-basica/tipo/(?P<tipo>[\w-]+)/$', 'canasta_basica'),
                        (r'^economico/canasta-basica/(?P<ano_inicial>\d{4})/$', 'canasta_basica'),
                        (r'^economico/canasta-basica/(?P<ano_inicial>\d{4})/tipo/(?P<tipo>[\w-]+)/$', 'canasta_basica'),
                        (r'^economico/canasta-basica/(?P<ano_inicial>\d{4})-(?P<ano_final>\d{4})/$', 'canasta_basica'),
                        (r'^economico/canasta-basica/(?P<ano_inicial>\d{4})-(?P<ano_final>\d{4})/tipo/(?P<tipo>\w+)/$', 'canasta_basica'),
                        #grafo canasta basica
                        (r'^economico/grafo/canasta-basica/$', 'grafo_canasta_basica'),
                        (r'^economico/grafo/canasta-basica/tipo/(?P<tipo>[\w-]+)/$', 'grafo_canasta_basica'),
                        (r'^economico/grafo/canasta-basica/(?P<ano_inicial>\d{4})/$', 'grafo_canasta_basica'),
                        (r'^economico/grafo/canasta-basica/(?P<ano_inicial>\d{4})/tipo/(?P<tipo>[\w-]+)/$', 'grafo_canasta_basica'),
                        (r'^economico/grafo/canasta-basica/(?P<ano_inicial>\d{4})-(?P<ano_final>\d{4})/$', 'grafo_canasta_basica'),
                        (r'^economico/grafo/canasta-basica/(?P<ano_inicial>\d{4})-(?P<ano_final>\d{4})/tipo/(?P<tipo>\w+)/$', 'grafo_canasta_basica'),
                        #mercados
                        (r'^economico/mercados/$', 'mercados'),
                        (r'^economico/mercados/departamento/(?P<departamento>\d+)/$', 'mercados'),
                        (r'^economico/mercados/municipio/(?P<municipio>\d+)/$', 'mercados'),
                        #empleo
                        (r'^economico/empleo/$', 'empleo'),
                        (r'^economico/empleo/(?P<ano_inicial>\d{4})/$', 'empleo'),
                        (r'^economico/empleo/(?P<ano_inicial>\d{4})-(?P<ano_final>\d{4})/$', 'empleo'),
                        #salario minimo
                        (r'^economico/salario-minimo/$', 'salario_minimo'),
                        (r'^economico/salario-minimo/sector/(?P<sector>[\w-]+)/$', 'salario_minimo'),
                        (r'^economico/salario-minimo/(?P<ano_inicial>\d{4})/$', 'salario_minimo'),
                        (r'^economico/salario-minimo/(?P<ano_inicial>\d{4})/sector/(?P<sector>[\w-]+)/$', 'salario_minimo'),
                        (r'^economico/salario-minimo/(?P<ano_inicial>\d{4})-(?P<ano_final>\d{4})/$', 'salario_minimo'),
                        (r'^economico/salario-minimo/(?P<ano_inicial>\d{4})-(?P<ano_final>\d{4})/sector/(?P<sector>\w+)/$', 'salario_minimo'),
                        #grafo salario minimo
                        (r'^economico/grafo/salario-minimo/$', 'grafo_salario_minimo'),
                        (r'^economico/grafo/salario-minimo/sector/(?P<sector>[\w-]+)/$', 'grafo_salario_minimo'),
                        (r'^economico/grafo/salario-minimo/(?P<ano_inicial>\d{4})/$', 'grafo_salario_minimo'),
                        (r'^economico/grafo/salario-minimo/(?P<ano_inicial>\d{4})/sector/(?P<sector>[\w-]+)/$', 'grafo_salario_minimo'),
                        (r'^economico/grafo/salario-minimo/(?P<ano_inicial>\d{4})-(?P<ano_final>\d{4})/$', 'grafo_salario_minimo'),
                        (r'^economico/grafo/salario-minimo/(?P<ano_inicial>\d{4})-(?P<ano_final>\d{4})/sector/(?P<sector>\w+)/$', 'grafo_salario_minimo'),
                        #salario nominal real
                        (r'^economico/salario-nominal-real/$', 'salario_nominal_real'),
                        (r'^economico/salario-nominal-real/(?P<ano_inicial>\d{4})/$', 'salario_nominal_real'),
                        (r'^economico/salario-nominal-real/(?P<ano_inicial>\d{4})-(?P<ano_final>\d{4})/$', 'salario_nominal_real'),
                        #grafo salario nominal real
                        (r'^economico/grafo/salario-nominal-real/$', 'grafo_salario_nominal_real'),
                        (r'^economico/grafo/salario-nominal-real/(?P<ano_inicial>\d{4})/$', 'grafo_salario_nominal_real'),
                        (r'^economico/grafo/salario-nominal-real/(?P<ano_inicial>\d{4})-(?P<ano_final>\d{4})/$', 'grafo_salario_nominal_real'),
                       )

urls.py
from django.conf.urls.defaults import *
from os import path as os_path
from django.conf import settings
import economico.views
# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()


urlpatterns = patterns('',
    (r'^admin/(.*)', admin.site.root),
    (r'^', include('economico.urls')),
    (r'^seguridad-alimentaria/', include('seguridad_alimentaria.urls')),
    (r'^demografico/', include('demografico.urls')),
    (r'^ajax/municipio/(?P<departamento>\d+)/$', 'lugar.views.get_municipios'),
)

if settings.DEBUG:
    urlpatterns += patterns('',
            (r'^css/(.*)$', 'django.views.static.serve',
                {'document_root': os_path.join(settings.MEDIA_ROOT + '/css')}),
            (r'^js/(.*)$', 'django.views.static.serve',
                {'document_root': os_path.join(settings.MEDIA_ROOT + '/js')}),
            (r'^imagen/(.*)$', 'django.views.static.serve',
                {'document_root': os_path.join(settings.MEDIA_ROOT + '/imagen')}),
)

economico/models.py
# -*- coding: UTF-8 -*-
from django.db import models
import datetime
from lugar.models import Departamento, Municipio

ANO_CHOICES=[]
for i in range (datetime.date.today().year,1989,-1):
	ANO_CHOICES.append((i,str(i)))

MES_CHOICES = (
    (1, 'Enero'),(2, 'Febrero'),(3, 'Marzo'),(4, 'Abril'),(5, 'Mayo'),(6, 'Junio'),(7, 'Julio'),(8, 'Agosto'),(9, 'Septiembre'), (10, 'Octubre'),(11, 'Noviembre'),(12, 'Diciembre')
)

#class Exportacion(models.Model):
#	ano = models.IntegerField("Ano",max_length=5, choices=CHOICESANO, help_text='Introduzca el ano')
#	mes = models.IntegerField("Mes",max_length=2, choices=CHOICESMES, help_text='Introduzca el mes')
#	fob = models.DecimalField("FOB",max_digits=10,decimal_places=2)
#
#	class Meta:
#		ordering = ['ano']
#		unique_together = ['ano','mes']
#		verbose_name_plural = "Indicador de Exportaciones de Mercancias FOB"

	#def __unicode__(self):
	#	return self.ano

class Sector(models.Model):
    nombre = models.CharField("Nombre del Sector", max_length=50, unique=True)
    slug = models.SlugField(unique=True, null=True)

    def __unicode__(self):
        return self.nombre
    
    class Meta:
        verbose_name_plural='Sectores'

class SalarioMinimo(models.Model):
    ano = models.IntegerField("Año", max_length=4, choices=ANO_CHOICES)
    mes = models.IntegerField("Mes", max_length=2, choices=MES_CHOICES)
    sector = models.ForeignKey(Sector)
    salario = models.DecimalField("Salario", max_digits=10, decimal_places=2)

    def __unicode__(self):
        return "Salario Minimo sector %s (%s-%s)" % (self.sector.nombre, self.mes, self.ano)

    class Meta:
        unique_together=['ano','mes','sector']
        ordering = ['ano']
        verbose_name_plural = "indicador de salario minimo"
        verbose_name = verbose_name_plural

class TipoCanastaBasica(models.Model):
    tipo = models.CharField("Tipo", unique=True, max_length=30)
    slug = models.SlugField("slug", unique=True, max_length=50, blank=True, null=True)

    def __unicode__(self):
        return self.tipo

    class Meta:
        verbose_name_plural='Tipos de Canastas Basicas'

class CanastaBasica(models.Model):
    ano = models.IntegerField("Año", max_length=4, choices=ANO_CHOICES)
    tipo = models.ForeignKey(TipoCanastaBasica, null=True, blank=True)
    mes = models.IntegerField("Mes", max_length=2, choices=MES_CHOICES)
    costo = models.DecimalField("Costo", max_digits=14, decimal_places=2)

    def __unicode__(self):
        return "Canasta Basica %s-%s" % (self.mes, self.ano)

    class Meta:
        ordering = ['tipo', 'ano', 'mes']
        unique_together=['tipo','mes', 'ano']

class SalarioNominal(models.Model):
    ano = models.IntegerField("Año", max_length=4, choices=ANO_CHOICES)
    mes = models.IntegerField("Mes", max_length=2, choices=MES_CHOICES)
    asegurados_inss = models.DecimalField("Asegurados del INSS", max_digits=10, decimal_places=2)
    gobierno_central = models.DecimalField("Gobierno Central", max_digits=10, decimal_places=2)
    salario_nacional = models.DecimalField("Salario nacional", max_digits=10, decimal_places=2)

    def __unicode__(self):
        return "Salario Nominal %s-%s" % (self.mes, self.ano)

    class Meta:
        unique_together=['ano','mes']
        ordering = ['ano', 'mes']
        verbose_name_plural = "indicador de salario nominal"
        verbose_name = verbose_name_plural

class SalarioReal(models.Model):
    ano = models.IntegerField("Año", max_length=4, choices=ANO_CHOICES)
    mes = models.IntegerField("Mes", max_length=2, choices=MES_CHOICES)
    asegurados_inss = models.DecimalField("Asegurados del INSS", max_digits=10, decimal_places=2)
    gobierno_central = models.DecimalField("Gobierno Central", max_digits=10, decimal_places=2)
    salario_nacional = models.DecimalField("Salario nacional", max_digits=10, decimal_places=2)

    def __unicode__(self):
        return "Salario Real %s-%s" % (self.mes, self.ano)

    class Meta:
        unique_together=['ano', 'mes']
        ordering = ['ano', 'mes']
        verbose_name_plural = "indicador de salario Real"
        verbose_name = verbose_name_plural

class Mercado(models.Model):
    ano = models.IntegerField("Año", max_length=4, choices=ANO_CHOICES)
    departamento = models.ForeignKey(Departamento)
    municipio = models.ForeignKey(Municipio)
    nombre = models.CharField("Nombre", max_length=100)
    ubicacion = models.TextField("Ubicacion")

    def __unicode__(self):
        return "Mercado: %s en %s, %s" % (self.nombre, self.municipio.nombre, self.departamento.nombre)

    class Meta:
        unique_together = ['ano', 'nombre']
        ordering = ['nombre']

class FuerzaTrabajo(models.Model):
    ano = models.IntegerField("Año", max_length=4, choices=ANO_CHOICES)
    poblacion_total = models.IntegerField()
    poblacion_mayor_10 = models.IntegerField()
    pea_general = models.IntegerField()
    total_ocupados = models.IntegerField()
    ocupados_actividad_primaria = models.IntegerField()
    agricultura_pecuaria = models.IntegerField()
    silvicultura = models.IntegerField()
    pesca = models.IntegerField()
    ocupados_actividad_secundaria = models.IntegerField()
    manufactura = models.IntegerField("Industria Manufacturera")
    construccion = models.IntegerField("Construccion")
    minas_canteras = models.IntegerField("Minas y Canteras")
    ocupados_actividad_terciaria = models.IntegerField("Ocupados Actividad Terciaria")
    comercio = models.IntegerField()
    gobierno_central = models.IntegerField()
    transporte_comunicacion = models.IntegerField("Transporte y Comunicacion")
    establecimientos_financieros = models.IntegerField("Establecimientos Financieros")
    electricidad_gas_agua = models.IntegerField("Electricidad Gas y Agua") 
    desempleo_abierto = models.IntegerField("Desempleo Abierto", editable=False) #se calcula
    servicios_sociales = models.DecimalField("Serv. Soc. Comun. y Personales", max_digits=10, decimal_places=2, default = 0) 

    def __unicode__(self):
        return "Fuerza de Trabajo: %s" %  self.ano

    def save(self, force_insert=False, force_update=False):
        self.desempleo_abierto = self.pea_general - self.total_ocupados 
        super(FuerzaTrabajo, self).save(force_insert, force_update)

    class Meta:
        ordering = ['ano']
        verbose_name = 'Fuerza de Trabajo'
        verbose_name_plural = verbose_name

templates/economico/canasta_basica.html
{% extends 'base.html' %}
{%block tab%}'tabs-3'{%endblock%}
{%block extrahead%}
<script type="text/javascript">
$(document).ready(function(){
var flip = 0;
var cadena = window.location.pathname.split("/");
var tope = cadena.length - 2;
var parametros = '/';
for(i=3; i<=tope; i++)
{
    parametros+= cadena[i] + "/";
}
var url = "/economico/grafo/canasta-basica" + parametros;
$("#boton-grafo").click(function () { 
    $.getJSON(url, 
       function(data){
           if(flip++ % 2 == 0){
               $("#grafo").replaceWith('<div id="grafo"><img src="' + data.url + '" /></div>');
           }else{
               $("#grafo").replaceWith('<div id="grafo"></div>');
           }
       });
   });   
});   
</script>
{%endblock%}
{% block contenido %}
<script type="text/javascript">
    function procesarFormulario(form){
        var ano_inicial = form.ano_inicial.value;
        var ano_final= form.ano_final.value;
        var tipo = form.tipo.value;

        if (ano_inicial && ano_final)
        {
            if(tipo){
                var url = "/economico/canasta-basica/" + ano_inicial + "-" + ano_final + "/tipo/" + tipo + "/";
            }else{
                var url = "/economico/canasta-basica/" + ano_inicial + "-" + ano_final + "/";
            }
        }else if(ano_inicial){
            if(tipo){
                var url = "/economico/canasta-basica/" + ano_inicial + "/tipo/" + tipo + "/";
            }else{
                var url = "/economico/canasta-basica/" + ano_inicial + "/";
            }
        }else{
            if(tipo){
                var url = "/economico/canasta-basica/tipo/" + tipo + "/";
            }else{
                var url = "/economico/canasta-basica/";
            }
        }
        window.location = url;
    }
</script>
<form name="formulario" id="id_formulario" method="GET" action="">
    Año Inicial:
    <select name="ano_inicial" id="id_ano_inicial">
        <option value="">-------</option>
        {%for ano in rango%}
        <option value="{{ano}}">{{ano}}</option>
        {%endfor%}
    </select>
    Año Final:
    <select name="ano_final" id="id_ano_final">
        <option value="">-------</option>
        {%for ano in rango reversed%}
        <option value="{{ano}}">{{ano}}</option>
        {%endfor%}
    </select>
    Tipo:
    <select name="tipo" id="id_tipo">
        <option value="">-------</option>
        {%for tipo in tipos_all%}
        <option value="{{tipo.slug}}">{{tipo.tipo}}</option>
        {%endfor%}
    </select>
    <input type="button" value="Filtar" name="boton" id="id_boton" onClick="procesarFormulario(this.form)"/>
</form>
<div id="boton-grafo"><a href="#">Gráfico</a></div>
<div id="grafo"></div>
Canasta Básica
<table>
    <tr>
        <th class="sortable-numeric">
            Año
        </th>
        {%for columna in columnas%}
        <th class="sortable-numeric">
            {{columna}}
        </th>
        {%endfor%}
    </tr>
    {%for fila in datos reversed%}
    <tr class="{%cycle alt, none%}">
        <td>
            <a href="/economico/canasta-basica/{{fila.ano}}/">{{fila.ano}}</a>
        </td>
        {%for coso in fila.datos%}
        <td>
            {{coso|floatformat:2}}
        </td>
        {%endfor%}
    </tr>
    {%endfor%}
    <tr>
        <td>
            Variaciones
        </td>
        {%for variacion in variaciones%}
        <td>
            {{variacion|floatformat:2}}%
        </td>
        {%endfor%}
    </tr>
</table>
{% endblock %}

templates/economico/canasta_basica_mes.html
{% extends 'base.html' %}
{%block tab%}'tabs-3'{%endblock%}
{%block extrahead%}
<script type="text/javascript">
$(document).ready(function(){
var flip = 0;
var cadena = window.location.pathname.split("/");
var tope = cadena.length - 2;
var parametros = '/';
for(i=3; i<=tope; i++)
{
    parametros+= cadena[i] + "/";
}
var url = "/economico/grafo/canasta-basica" + parametros;
$("#boton-grafo").click(function () { 
    $.getJSON(url, 
       function(data){
           if(flip++ % 2 == 0){
               $("#grafo").replaceWith('<div id="grafo"><img src="' + data.url + '" /></div>');
           }else{
               $("#grafo").replaceWith('<div id="grafo"></div>');
           }
       });
   });   
});   
</script>
{%endblock%}
{% block contenido %}
<script type="text/javascript">
    function procesarFormulario(form){
        var ano_inicial = form.ano_inicial.value;
        var ano_final= form.ano_final.value;
        var tipo = form.tipo.value;

        if (ano_inicial && ano_final)
        {
            if(sector){
                var url = "/economico/canasta-basica/" + ano_inicial + "-" + ano_final + "/tipo/" + tipo + "/";
            }else{
                var url = "/economico/canasta-basica/" + ano_inicial + "-" + ano_final + "/";
            }
        }else if(ano_inicial){
            if(sector){
                var url = "/economico/canasta-basica/" + ano_inicial + "/tipo/" + tipo + "/";
            }else{
                var url = "/economico/canasta-basica/" + ano_inicial + "/";
            }
        }else{
            if(sector){
                var url = "/economico/salario-minimo/sector/" + sector + "/";
            }else{
                var url = "/economico/salario-minimo/";
            }
        }
        window.location = url;
    }
</script>
<form name="formulario" id="id_formulario" method="GET" action="">
    Año Inicial:
    <select name="ano_inicial" id="id_ano_inicial">
        <option value="">-------</option>
        {%for ano in rango%}
        <option value="{{ano}}">{{ano}}</option>
        {%endfor%}
    </select>
    Año Final:
    <select name="ano_final" id="id_ano_final">
        <option value="">-------</option>
        {%for ano in rango reversed%}
        <option value="{{ano}}">{{ano}}</option>
        {%endfor%}
    </select>
    Tipo:
    <select name="tipo" id="id_tipo">
        <option value="">-------</option>
        {%for tipo in tipos_all%}
        <option value="{{tipo.slug}}">{{tipo.nombre}}</option>
        {%endfor%}
    </select>
    <input type="button" value="Filtar" name="boton" id="id_boton" onClick="procesarFormulario(this.form)"/>
</form>
<div id="boton-grafo"><a href="#">Gráfico</a></div>
<div id="grafo"></div>
Canasta Básica
<table>
    <tr>
        <th class="sortable-numeric">
            Año
        </th>
        <th class="sortable-numeric">
           Mes 
        </th>
        {%for columna in columnas%}
        <th class="sortable-numeric">
            {{columna}}
        </th>
        {%endfor%}
    </tr>
    {%for fila in datos%}
    <tr class="{%cycle alt, none%}">
        <td>
            {{fila.ano}}
        </td>
        <td>
            {{fila.mes}}
        </td>
        {%for valor in fila.datos%}
        <td>
            {{valor}}
        </td>
        {%endfor%}
    </tr>
    {%endfor%}
</table>
{% endblock %}

templates/economico/canasta_basica_tipo.html
{% extends 'base.html' %}

{% block contenido %}
<table>
    <tr>
        <td>
            Año
        </td>
        <td>
           Mes 
        </td>
        {%for columna in columnas%}
        <td>
            {{columna}}
        </td>
        {%endfor%}
    </tr>
    {%for fila in datos%}
    <tr>
        {%for item in fila%}
        <td>
            {{item}}
        </td>
        {%endfor%}
    </tr>
    {%endfor%}
</table>
{% endblock %}

templates/economico/index.html
{% extends 'base.html' %}
{%block tab%}'tabs-1'{%endblock%}

{% block contenido %}
fooo
{% endblock %}

templates/economico/mercados.html
{% extends 'base.html' %}
{%block tab%}'tabs-3'{%endblock%}
{% block contenido %}
{{mensaje}}
<script type="text/javascript">
$(document).ready(function () {
    var departamento = document.getElementById("id_departamento");
    var municipio = document.getElementById("id_municipio");
    $("#id_departamento").change(function () {
      var index = departamento.options.selectedIndex;
      var id = departamento.options[index].value;
      $.getJSON("/ajax/municipio/" + id +"/",
      function(data){
        municipio.options.length = 0;
        //municipio.options[0] = new Option("--------");
        for(i=0; i< data.length; i++){
          municipio.options[i+1] = new Option(data[i][1], data[i][0]);
        }
      });
    });
});
function procesarFormulario(form){
    var dept = form.departamento.value;
    var muni = form.municipio.value;
    if (dept && muni){
        var url = "/economico/mercados/municipio/" + muni + "/";
    }else if(dept){
        var url = "/economico/mercados/departamento/" + dept + "/";
    }else{
        var url="/economico/mercados/";
    }
    window.location = url;
}
</script>
<form name="formulario" id="id_formulario" action="" method="GET">
    Departamentos: 
    <select id="id_departamento" name="departamento">
        <option selected="selected"  value="">------</option>
        {%for dept in departamentos%}
        <option value="{{dept.id}}">{{dept.nombre}}</option>
        {%endfor%}
    </select>
    Municipios: 
    <select id="id_municipio" name="municipio">
        <option selected="selected"  value="">------</option>
    </select>
        <input type="button" name="boton" id="id_boton" value="Filtrar"  onClick="procesarFormulario(this.form)"/>
</form>
<table>
    <tr>
        <th class="sortable-numeric">
            Año
        </th>
        <th class="sortable-numeric">
          Departamento 
        </th>
        <th class="sortable-numeric">
           Municipio 
        </th>
        <th class="sortable-numeric">
          Nombre 
        </th>
        <th class="sortable-numeric">
          Ubicación 
        </th>
    </tr>
    {%for mercado in mercados%}
    <tr class="{%cycle alt, none%}">
        <td>
            {{mercado.ano}}
        </td>
        <td>
            <a href="/economico/mercados/departamento/{{mercado.departamento.slug}}/">{{mercado.departamento.nombre}}</a>
        </td>
        <td>
            <a href="/economico/mercados/municipio/{{mercado.municipio.slug}}/">{{mercado.municipio.nombre}}</a>
        </td>
        <td>
            {{mercado.nombre}}
        </td>
        <td>
            {{mercado.ubicacion}}
        </td>
    </tr>
    {%endfor%}
</table>
{% endblock %}

templates/economico/salario_minimo.html
{% extends 'base.html' %}
{%block tab%}'tabs-3'{%endblock%}
{%block extrahead%}
<script type="text/javascript">
$(document).ready(function(){
var flip = 0;
var cadena = window.location.pathname.split("/");
var tope = cadena.length - 2;
var parametros = '/';
for(i=3; i<=tope; i++)
{
    parametros+= cadena[i] + "/";
}
var url = "/economico/grafo/salario-minimo" + parametros;
$("#boton-grafo").click(function () { 
    $.getJSON(url, 
       function(data){
           if(flip++ % 2 == 0){
               $("#grafo").replaceWith('<div id="grafo"><img src="' + data.url + '" /></div>');
           }else{
               $("#grafo").replaceWith('<div id="grafo"></div>');
           }
       });
   });   
});   
</script>
{%endblock%}
{% block contenido %}
<script type="text/javascript">
    function procesarFormulario(form){
        var ano_inicial = form.ano_inicial.value;
        var ano_final= form.ano_final.value;
        var sector = form.sector.value;

        if (ano_inicial && ano_final)
        {
            if(sector){
                var url = "/economico/salario-minimo/" + ano_inicial + "-" + ano_final + "/sector/" + sector + "/";
            }else{
                var url = "/economico/salario-minimo/" + ano_inicial + "-" + ano_final + "/";
            }
        }else if(ano_inicial){
            if(sector){
                var url = "/economico/salario-minimo/" + ano_inicial + "/sector/" + sector + "/";
            }else{
                var url = "/economico/salario-minimo/" + ano_inicial + "/";
            }
        }else{
            if(sector){
                var url = "/economico/salario-minimo/sector/" + sector + "/";
            }else{
                var url = "/economico/salario-minimo/";
            }
        }
        window.location = url;
    }
</script>

<form name="formulario" id="id_formulario" method="GET" action="">
    Año Inicial:
    <select name="ano_inicial" id="id_ano_inicial">
        <option value="">-------</option>
        {%for ano in rango%}
        <option value="{{ano}}">{{ano}}</option>
        {%endfor%}
    </select>
    Año Final:
    <select name="ano_final" id="id_ano_final">
        <option value="">-------</option>
        {%for ano in rango reversed%}
        <option value="{{ano}}">{{ano}}</option>
        {%endfor%}
    </select>
    Sector:
    <select name="sector" id="id_sector">
        <option value="">-------</option>
        {%for sector in sectores_all%}
        <option value="{{sector.slug}}">{{sector.nombre}}</option>
        {%endfor%}
    </select>
    <input type="button" value="Filtar" name="boton" id="id_boton" onClick="procesarFormulario(this.form)"/>
</form>
<div id="boton-grafo"><a href="#">Gráfico</a></div>
<div id="grafo"></div>
Salario Mínimo
<table>
    <tr>
        <th class="sortable-numeric">
            Año
        </th>
        {%if tiene_mes%}
        <th class="sortable-numeric">
            Mes
        </th>
        {%endif%}
        {%for sector in sectores%}
        <th class="sortable-numeric">
            {{sector.nombre}}
        </th>
        {%endfor%}
    </tr>
    {%for fila in datos %}
    <tr class="{%cycle alt, none%}">
        <td>
            <a href="/economico/salario-minimo/{{fila.ano}}/">{{fila.ano}}</a>
        </td>
        {%if tiene_mes%}
        <td>
            {{fila.mes}}
        </td>
        {%endif%}
        {%for coso in fila.datos%}
        <td>
            {{coso}}
        </td>
        {%endfor%}
    </tr>
    {%endfor%}
    <tfoot>
    <tr>
        {%if tiene_mes%}
        <th colspan="2">
           promedio
        </th>
        {%for promedio in promedios%}
        <th>
            {{promedio|floatformat:2}}
        </th>
        {%endfor%}
        {%else%}
        <th>
            variaciones
        </th>
        {%for variacion in variaciones%}
        <th>
            {{variacion}}
        </th>
        {%endfor%}
        {%endif%}
    </tr>
</tfoot>
</table>
{% endblock %}