seguridad_alimentaria/urls.py
from django.conf.urls.defaults import *
from django.conf import settings
 
urlpatterns = patterns('seguridad_alimentaria.views',
                        (r'^$', 'index'),
                        #utilizacion biologica
                        (r'^utilizacion-biologica/$', 'utilizacion_biologica'),
                        (r'^utilizacion-biologica/(?P<ano_inicial>\d{4})-(?P<ano_final>\d{4})/$', 'utilizacion_biologica'),
                        (r'^utilizacion-biologica/(?P<ano_inicial>\d{4})/$', 'utilizacion_biologica'),
                        (r'^utilizacion-biologica/(?P<departamento>\w+)/$', 'utilizacion_biologica'),
                        (r'^utilizacion-biologica/(?P<ano_inicial>\d{4})-(?P<ano_final>\d{4})/(?P<departamento>\w+)/$', 'utilizacion_biologica'),
                        (r'^utilizacion-biologica/(?P<ano_inicial>\d{4})/(?P<departamento>\w+)/$', 'utilizacion_biologica'),
                        #grafo utilizacion biologica
                        (r'^grafo/utilizacion-biologica/$', 'grafo_utilizacion_biologica'),
                        (r'^grafo/utilizacion-biologica/(?P<ano_inicial>\d{4})-(?P<ano_final>\d{4})/$', 'grafo_utilizacion_biologica'),
                        (r'^grafo/utilizacion-biologica/(?P<ano_inicial>\d{4})/$', 'grafo_utilizacion_biologica'),
                        (r'^grafo/utilizacion-biologica/(?P<departamento>\w+)/$', 'grafo_utilizacion_biologica'),
                        (r'^grafo/utilizacion-biologica/(?P<ano_inicial>\d{4})-(?P<ano_final>\d{4})/(?P<departamento>\w+)/$', 'grafo_utilizacion_biologica'),
                        (r'^grafo/utilizacion-biologica/(?P<ano_inicial>\d{4})/(?P<departamento>\w+)/$', 'grafo_utilizacion_biologica'),
                        #dependencia alimentaria
                        (r'^dependencia-alimentaria/$', 'dependencia_alimentaria'),
                        (r'^dependencia-alimentaria/(?P<ano_inicial>\d{4})/$', 'dependencia_alimentaria'),
                        (r'^dependencia-alimentaria/(?P<ano_inicial>\d{4})-(?P<ano_final>\d{4})/$', 'dependencia_alimentaria'),
                        #grafo dependencia alimentaria
                        (r'^grafo/dependencia-alimentaria/$', 'grafo_dependencia_alimentaria'),
                        (r'^grafo/dependencia-alimentaria/(?P<ano_inicial>\d{4})/$', 'grafo_dependencia_alimentaria'),
                        (r'^grafo/dependencia-alimentaria/(?P<ano_inicial>\d{4})-(?P<ano_final>\d{4})/$', 'grafo_dependencia_alimentaria'),
                        (r'^grafo/dependencia-alimentaria/(?P<ano_inicial>\d{4})/(?P<producto>\w+)/$', 'grafo_dependencia_alimentaria_producto'),
                        (r'^grafo/dependencia-alimentaria/(?P<ano_inicial>\d{4})-(?P<ano_final>\d{4})/(?P<producto>\w+)/$', 'grafo_dependencia_alimentaria_producto'),
                        (r'^grafo/dependencia-alimentaria/(?P<producto>\w+)/$', 'grafo_dependencia_alimentaria_producto'),
                        #dependencia alimentaria por producto
                        (r'^dependencia-alimentaria/(?P<ano_inicial>\d{4})/(?P<producto>\w+)/$', 'dependencia_alimentaria_producto'),
                        (r'^dependencia-alimentaria/(?P<ano_inicial>\d{4})-(?P<ano_final>\d{4})/(?P<producto>\w+)/$', 'dependencia_alimentaria_producto'),
                        (r'^dependencia-alimentaria/(?P<producto>\w+)/$', 'dependencia_alimentaria_producto'),
                        #disponibilidad
                        (r'^disponibilidad/$', 'disponibilidad'),
                        (r'^disponibilidad/(?P<ano_inicial>\d{4})/$', 'disponibilidad'),
                        (r'^disponibilidad/(?P<ano_inicial>\d{4})-(?P<ano_final>\d{4})/$', 'disponibilidad'),
                        (r'^disponibilidad/(?P<ano_inicial>\d{4})/(?P<producto>\w+)/$', 'disponibilidad'),
                        (r'^disponibilidad/(?P<ano_inicial>\d{4})-(?P<ano_final>\d{4})/(?P<producto>\w+)/$', 'disponibilidad'),
                        (r'^disponibilidad/(?P<producto>\w+)/$', 'disponibilidad'),
                        #grafos disponibilidad
                        (r'^grafo/disponibilidad/$', 'grafo_disponibilidad'),
                        (r'^grafo/disponibilidad/(?P<ano_inicial>\d{4})/$', 'grafo_disponibilidad'),
                        (r'^grafo/disponibilidad/(?P<ano_inicial>\d{4})-(?P<ano_final>\d{4})/$', 'grafo_disponibilidad'),
                        (r'^grafo/disponibilidad/(?P<ano_inicial>\d{4})/(?P<producto>\w+)/$', 'grafo_disponibilidad'),
                        (r'^grafo/disponibilidad/(?P<ano_inicial>\d{4})-(?P<ano_final>\d{4})/(?P<producto>\w+)/$', 'grafo_disponibilidad'),
                        (r'^grafo/disponibilidad/(?P<producto>\w+)/$', 'grafo_disponibilidad'),
                        #Apertura comercial
                        (r'^apertura-comercial/$', 'apertura_comercial'),
                        (r'^apertura-comercial/(?P<ano_inicial>\d{4})/$', 'apertura_comercial'),
                        (r'^apertura-comercial/(?P<ano_inicial>\d{4})-(?P<ano_final>\d{4})/$', 'apertura_comercial'),
                        #grafos apertura comercial
                        (r'^grafo/apertura-comercial/$', 'grafo_apertura_comercial'),
                        (r'^grafo/apertura-comercial/(?P<ano_inicial>\d{4})/$', 'grafo_apertura_comercial'),
                        (r'^grafo/apertura-comercial/(?P<ano_inicial>\d{4})-(?P<ano_final>\d{4})/$', 'grafo_apertura_comercial'),
                       )

urls.py
from django.conf.urls.defaults import *
from os import path as os_path
from django.conf import settings
import economico.views
# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()


urlpatterns = patterns('',
    (r'^admin/(.*)', admin.site.root),
    (r'^', include('economico.urls')),
    (r'^seguridad-alimentaria/', include('seguridad_alimentaria.urls')),
    (r'^demografico/', include('demografico.urls')),
    (r'^ajax/municipio/(?P<departamento>\d+)/$', 'lugar.views.get_municipios'),
)

if settings.DEBUG:
    urlpatterns += patterns('',
            (r'^css/(.*)$', 'django.views.static.serve',
                {'document_root': os_path.join(settings.MEDIA_ROOT + '/css')}),
            (r'^js/(.*)$', 'django.views.static.serve',
                {'document_root': os_path.join(settings.MEDIA_ROOT + '/js')}),
            (r'^imagen/(.*)$', 'django.views.static.serve',
                {'document_root': os_path.join(settings.MEDIA_ROOT + '/imagen')}),
)

seguridad_alimentaria/models.py
from django.db import models
import datetime
from lugar.models import Departamento

ANO_CHOICES=[]
for i in range (datetime.date.today().year,1989,-1):
	ANO_CHOICES.append((i,str(i)))
#disp y consumo aparente

class Producto(models.Model):
    nombre = models.CharField("Nombre del Producto", max_length=20)
    slug = models.SlugField("url limpia", null=True)

    def __unicode__(self):
        return self.nombre

class DependenciaAlimentaria(models.Model):
    ano = models.IntegerField("Ano", max_length=4, choices=ANO_CHOICES)
    producto = models.ForeignKey(Producto)
    area = models.DecimalField(help_text = "miles de manzanas", max_digits=10, decimal_places=2)
    produccion = models.DecimalField(max_digits=10, decimal_places=2, help_text="en miles de quintales")
    rendimiento= models.DecimalField(max_digits=10, decimal_places=2, editable=False)
    donaciones = models.DecimalField(max_digits=10, decimal_places=2, help_text="en miles de quintales")
    exportaciones = models.DecimalField(max_digits=10, decimal_places=2, help_text="en miles de quintales")
    importaciones = models.DecimalField(max_digits=10, decimal_places=2, help_text="en miles de quintales")
    dependencia_alimentaria = models.DecimalField(max_digits=10, decimal_places=2, editable=False)
    porcentaje = models.DecimalField(max_digits=10, decimal_places=2, editable=False)

    def save(self, force_insert=False, force_update=False):
        self.rendimiento = self.produccion/self.area
        self.dependencia_alimentaria = self.produccion + self.importaciones + self.donaciones - self.exportaciones
        self.porcentaje = ((self.importaciones + self.donaciones)/self.dependencia_alimentaria)*100 
        super(DependenciaAlimentaria, self).save(force_insert, force_update)

    def __unicode__(self):
        return "Dependencia alimentaria - %s (%s)" % (self.producto.nombre, self.ano)
    
    class Meta:
        unique_together=['ano', 'producto']
        ordering = ['ano', 'producto']
        verbose_name_plural = 'Dependencia Alimentaria'


class SoberaniaAlimentaria(models.Model):
    ano = models.IntegerField("Ano", max_length=4, choices=ANO_CHOICES)
    producto = models.ForeignKey(Producto)
    donaciones = models.DecimalField(max_digits=10, decimal_places=2)
    importaciones = models.DecimalField(max_digits=10, decimal_places=2)
    disponibilidad = models.DecimalField(max_digits=10, decimal_places=2)
    consumo_aparente= models.DecimalField(max_digits=10, decimal_places=2)

    def __unicode__(self):
        return "%s (%s)" % (self.producto.nombre, self.ano)

    class Meta:
        unique_together=['ano','producto']
        ordering=['ano', 'producto']
        verbose_name = "Soberania Alimentaria"
        verbose_name_plural = verbose_name

class UtilizacionBiologica(models.Model):
    ano = models.IntegerField("Ano", max_length=4, choices=ANO_CHOICES)
    departamento = models.ForeignKey(Departamento)
    enfermedades_diarreicas = models.DecimalField("Enfermedades diarreicas agudas", max_digits=10, decimal_places=2)
    enfermedades_respiratorias = models.DecimalField("Enfermedades respiratorias agudas", max_digits=10, decimal_places=2)

    def __unicode__(self):
        return "Utilizacion bioligica dept: %s (%s)" % (self.departamento.nombre, self.ano)

    class Meta:
        unique_together=['ano','departamento']
        ordering=['-ano']
        verbose_name = "Utilizacion Biologica"
        verbose_name_plural = verbose_name

class AperturaComercial(models.Model):
    ano = models.IntegerField("Ano", max_length=4, choices=ANO_CHOICES, unique=True)
    pib = models.DecimalField("PIB", decimal_places=2, max_digits=10)
    exportaciones = models.DecimalField("Exportaciones", decimal_places=2, max_digits=10)
    importaciones = models.DecimalField("Importaciones", decimal_places=2, max_digits=10)

    def __unicode__(self):
        return "Apertura Comercial (%s)" % self.ano

    class Meta:
        ordering=['-ano']
        verbose_name = "Apertura Comercial"
        verbose_name_plural = "Aperturas Comerciales"

templates/seguridad_alimentaria/apertura_comercial.html
{% extends 'base.html' %}
{%block tab%}'tabs-5'{%endblock%}
{%block extrahead%}
<script type="text/javascript">
$(document).ready(function(){
var flip = 0;
var cadena = window.location.pathname.split("/");
var tope = cadena.length - 2;
var parametros = '/';
for(i=3; i<=tope; i++)
{
    parametros+= cadena[i] + "/";
}
var url = "/" + cadena[1] + "/grafo/" + cadena[2] + parametros;
$("#boton-grafo").click(function () { 
    $.getJSON(url, 
       function(data){
           if(flip++ % 2 == 0){
               $("#grafo").replaceWith('<div id="grafo"><img src="' + data.url + '" /></div>');
           }else{
               $("#grafo").replaceWith('<div id="grafo"></div>');
           }
       });
   });   
});
</script>
{%endblock%}
{% block contenido %}
<script type="text/javascript">
    function procesarFormulario(form){
        var ano_inicial = form.ano_inicial.value;
        var ano_final = form.ano_final.value;

        if (ano_inicial && ano_final){
            var url = "/seguridad-alimentaria/apertura-comercial/" + ano_inicial + "-" + ano_final + "/";
        }else if(ano_inicial){
            var url = "/seguridad-alimentaria/apertura-comercial/" + ano_inicial + "/";
        }else{
            var url = "/seguridad-alimentaria/apertura-comercial/";
        }
        window.location = url;
    }
</script>
<form id="id_formulario" name="formulario" method="GET" action="">
    Año Inicial: 
    <select id="id_ano_inicial" name="ano_inicial">
        <option value="">-----</option>
        {%for ano in anos%}
        <option value="{{ano}}">{{ano}}</option>
        {%endfor%}
    </select>
    Año Final:
    <select id="id_ano_final" name="ano_final">
        <option value="">-----</option>
        {%for ano in anos reversed%}
        <option value="{{ano}}">{{ano}}</option>
        {%endfor%}
    </select>
    <input type="button" value="Filtrar" onClick="procesarFormulario(this.form)"/>
</form>
<div id="boton-grafo"><a href="#">Gráfico</a></div>
<div id="grafo"></div>
{{mensaje}}
<table>
    <tr>
        <th class="sortable-numeric">
            Año
        </th>
        <th class="sortable-numeric">
            Tasa
        </th>
    </tr>
    {%for dato in resultados reversed%}
    <tr>
        <td class="{% cycle alt, none%}">
            <a href="/seguridad-alimentaria/apertura-comercial/{{dato.ano}}"/>{{dato.ano}} </a>
        </td>
        <td class="{% cycle alt, none%}">
            {{dato.tasa|floatformat:2}}
        </td>
    </tr>
    {%endfor%}
    <tfoot>
    <tr>
        <td>
            Variación
        </td>
        <td>
            {{variacion|floatformat:2}}%
        </td>
    </tr>
</tfoot>
</table>
{% endblock %}

templates/seguridad_alimentaria/dependencia_alimentaria.html
{% extends 'base.html' %}
{%block tab%}'tabs-5'{%endblock%}
{%block extrahead%}
<script type="text/javascript">
$(document).ready(function(){
var flip = 0;
var cadena = window.location.pathname.split("/");
var tope = cadena.length - 2;
var parametros = '/';
for(i=3; i<=tope; i++)
{
    parametros+= cadena[i] + "/";
}
var url = "/" + cadena[1] + "/grafo/" + cadena[2] + parametros;
$("#boton-grafo").click(function () { 
    $.getJSON(url, 
       function(data){
           if(flip++ % 2 == 0){
               $("#grafo").replaceWith('<div id="grafo"><img src="' + data.url + '" /></div>');
           }else{
               $("#grafo").replaceWith('<div id="grafo"></div>');
           }
       });
   });   
});
</script>
{%endblock%}
{% block contenido %}
<script type="text/javascript">
    function procesarFormulario(form){
        var ano_inicial = form.ano_inicial.value;
        var ano_final = form.ano_final.value;
        var producto = form.producto.value;

        if (ano_inicial && ano_final){
            if (producto){
                var url = "/seguridad-alimentaria/dependencia-alimentaria/" + ano_inicial + "-" + ano_final + "/" + producto + "/";
            }else{
                var url = "/seguridad-alimentaria/dependencia-alimentaria/" + ano_inicial + "-" + ano_final + "/";
            }
        }else if(ano_inicial){
            if (producto){
                var url = "/seguridad-alimentaria/dependencia-alimentaria/" + ano_inicial +  "/" + producto + "/";
            }else{
                var url = "/seguridad-alimentaria/dependencia-alimentaria/" + ano_inicial + "/";
            }
        }else{
            if (producto){
                var url = "/seguridad-alimentaria/dependencia-alimentaria/" + producto + "/";
            }else{
                var url = "/seguridad-alimentaria/dependencia-alimentaria/";
            }
        }
        window.location = url;
    }
</script>
<form id="id_formulario" name="formulario" method="GET" action="">
    Año Inicial: 
    <select id="id_ano_inicial" name="ano_inicial">
        <option value="">-----</option>
        {%for ano in anos%}
        <option value="{{ano}}">{{ano}}</option>
        {%endfor%}
    </select>
    Año Final:
    <select id="id_ano_final" name="ano_final">
        <option value="">-----</option>
        {%for ano in anos reversed%}
        <option value="{{ano}}">{{ano}}</option>
        {%endfor%}
    </select>
    Producto:
    <select id="id_producto" name="producto">
        <option value="">----</option>
        {%for producto in productos_all%}
        <option value="{{producto.slug}}">{{producto.nombre}}</option>
        {%endfor%}
    </select>
    <input type="button" value="Filtrar" onClick="procesarFormulario(this.form)"/>
</form>
<div id="boton-grafo"><a href="#">Gráfico</a></div>
<div id="grafo"></div>
{{mensaje}}
<table>
    <tr>
        <th class="sortable-numeric">
            Año
        </th>
        {%for producto in productos%}
        <th class="sortable-numeric">
            {{producto.nombre}}
        </th>
        {%endfor%}
    </tr>
    {%for dato in resultados reversed%}
    <tr>
        <td class="{% cycle alt, none%}">
            <a href="/seguridad-alimentaria/dependencia-alimentaria/{{dato.ano}}"/> {{dato.ano}} </a>
        </td>
        {%for numero in dato.datos%}
        <td class="{% cycle alt, none%}">
            {{numero}}
        </td>
        {%endfor%}
    </tr>
    {%endfor%}
    <tfoot>
    <tr>
        <td>
            Variación
        </td>
        {%for variacion in variaciones%}
        <td>
            {{variacion}}%
        </td>
        {%endfor%}
    </tr>
    </tfoot>
</table>
{% endblock %}

templates/seguridad_alimentaria/disponibilidad.html
{% extends 'base.html' %}
{%block tab%}'tabs-5'{%endblock%}
{%block extrahead%}
<script type="text/javascript">
$(document).ready(function(){
var flip = 0;
var cadena = window.location.pathname.split("/");
var tope = cadena.length - 2;
var parametros = '/';
for(i=3; i<=tope; i++)
{
    parametros+= cadena[i] + "/";
}
var url = "/" + cadena[1] + "/grafo/" + cadena[2] + parametros;
$("#boton-grafo-disponibilidades").click(function () { 
    $.getJSON(url, 
       function(data){
           if(flip++ % 2 == 0){
               $("#grafo-disponibilidades").replaceWith('<div id="grafo-disponibilidades"><img src="' + data.url_disponibilidades + '" /></div>');
           }else{
           $("#grafo-disponibilidades").replaceWith('<div id="grafo-disponibilidades"></div>');
           }
       });
   });   
$("#boton-grafo-consumos").click(function () { 
    $.getJSON(url, 
       function(data){
           if(flip++ % 2 == 0){
               $("#grafo-consumos").replaceWith('<div id="grafo-consumos"><img src="' + data.url_consumos + '" /></div>');
           }else{
               $("#grafo-consumos").replaceWith('<div id="grafo-consumos"></div>');
           }
       });
   });
});
</script>
{%endblock%}

{% block contenido %}
<script type="text/javascript">
    function procesarFormulario(form){
        var ano_inicial = form.ano_inicial.value;
        var ano_final = form.ano_final.value;
        var producto = form.producto.value;

        if (ano_inicial && ano_final){
            if (producto){
                var url = "/seguridad-alimentaria/disponibilidad/" + ano_inicial + "-" + ano_final + "/" + producto + "/";
            }else{
                var url = "/seguridad-alimentaria/disponibilidad/" + ano_inicial + "-" + ano_final + "/";
            }
        }else if(ano_inicial){
            if (producto){
                var url = "/seguridad-alimentaria/disponibilidad/" + ano_inicial +  "/" + producto + "/";
            }else{
                var url = "/seguridad-alimentaria/disponibilidad/" + ano_inicial + "/";
            }
        }else{
            if (producto){
                var url = "/seguridad-alimentaria/disponibilidad/" + producto + "/";
            }else{
                var url = "/seguridad-alimentaria/disponibilidad/";
            }
        }
        window.location = url;
    }
</script>
<form id="id_formulario" name="formulario" method="GET" action="">
    Año Inicial: 
    <select id="id_ano_inicial" name="ano_inicial">
        <option value="">-----</option>
        {%for ano in anos%}
        <option value="{{ano}}">{{ano}}</option>
        {%endfor%}
    </select>
    Año Final:
    <select id="id_ano_final" name="ano_final">
        <option value="">-----</option>
        {%for ano in anos reversed%}
        <option value="{{ano}}">{{ano}}</option>
        {%endfor%}
    </select>
    Producto:
    <select id="id_producto" name="producto">
        <option value="">----</option>
        {%for producto in productos_all%}
        <option value="{{producto.slug}}">{{producto.nombre}}</option>
        {%endfor%}
    </select>
    <input type="button" value="Filtrar" onClick="procesarFormulario(this.form)"/>
</form>
<div id="boton-grafo-disponibilidades"><a href="#">Gráfico Disponbilidad</a></div>
<div id="boton-grafo-consumos"><a href="#">Gráfico Consumo Aparente</a></div>
<div id="grafo-consumos"></div>
<div id="grafo-disponibilidades"></div>
{{mensaje}}
<table>
    <tr>
        <th class="sortable-numeric">
            Año
        </th>
        {%for producto in productos%}
        <th class="sortable-numeric">
            {{producto.nombre}}
        </th>
        {%endfor%}
    </tr>
    <tr>
        <td>
            Disponibilidad
        </td>
    </tr>
    {%for dato in disponibilidades reversed%}
    <tr>
        <td class="{% cycle alt, none%}">
            <a href="/seguridad-alimentaria/disponibilidad/{{dato.ano}}"/> {{dato.ano}} </a>
        </td>
        {%for numero in dato.datos%}
        <td class="{% cycle alt, none%}">
            {{numero}}
        </td>
        {%endfor%}
    </tr>
    {%endfor%}
    <tr>
        <td>
            Variación
        </td>
        {%for variacion in var_disp%}
        <td>
            {{variacion}}%
        </td>
        {%endfor%}
    </tr>
    <tr>
        <td>
            Consumo Aparente
        </td>
    {%for dato in consumos reversed%}
    <tr>
        <td>
            <a href="/seguridad-alimentaria/disponibilidad/{{dato.ano}}"/> {{dato.ano}} </a>
        </td>
        {%for numero in dato.datos%}
        <td>
            {{numero}}
        </td>
        {%endfor%}
    </tr>
    {%endfor%}
    <tr>
        <td>
            Variación
        </td>
        {%for variacion in var_consumos%}
        <td>
            {{variacion}}%
        </td>
        {%endfor%}
    </tr>
</table>
{% endblock %}

templates/seguridad_alimentaria/utilizacion_biologica.html
{% extends 'base.html' %}
{%block tab%}'tabs-5'{%endblock%}
{%block extrahead%}
<script type="text/javascript">
$(document).ready(function(){
var flip = 0;
var cadena = window.location.pathname.split("/");
var tope = cadena.length - 2;
var parametros = '/';
for(i=3; i<=tope; i++)
{
    parametros+= cadena[i] + "/";
}
var url = "/" + cadena[1] + "/grafo/" + cadena[2] + parametros;
$("#boton-grafo").click(function () { 
    $.getJSON(url, 
       function(data){
           if(flip++ % 2 == 0){
               $("#grafo").replaceWith('<div id="grafo"><img src="' + data.url + '" /></div>');
           }else{
               $("#grafo").replaceWith('<div id="grafo"></div>');
           }
       });
   });   
});
</script>
{%endblock%}
{% block contenido %}
<script type="text/javascript">
    function procesarFormulario(form){
        var ano_inicial = form.ano_inicial.value;
        var ano_final = form.ano_final.value;
        var departamento  = form.departamento.value;

        if (ano_inicial && ano_final){
            if (departamento){
                var url = "/seguridad-alimentaria/utilizacion-biologica/" + ano_inicial + "-" + ano_final + "/" + departamento + "/";
            }else{
                var url = "/seguridad-alimentaria/utilizacion-biologica/" + ano_inicial + "-" + ano_final + "/";
            }
        }else if(ano_inicial){
            if (departamento){
                var url = "/seguridad-alimentaria/utilizacion-biologica/" + ano_inicial +  "/" + departamento + "/";
            }else{
                var url = "/seguridad-alimentaria/utilizacion-biologica/" + ano_inicial + "/";
            }
        }else{
            if (departamento){
                var url = "/seguridad-alimentaria/utilizacion-biologica/" + departamento + "/";
            }else{
                var url = "/seguridad-alimentaria/utilizacion-biologica/";
            }
        }
        window.location = url;
    }
</script>
<form id="id_formulario" name="formulario" method="GET" action="">
    Año Inicial: 
    <select id="id_ano_inicial" name="ano_inicial">
        <option value="">-----</option>
        {%for ano in anos%}
        <option value="{{ano}}">{{ano}}</option>
        {%endfor%}
    </select>
    Año Final:
    <select id="id_ano_final" name="ano_final">
        <option value="">-----</option>
        {%for ano in anos reversed%}
        <option value="{{ano}}">{{ano}}</option>
        {%endfor%}
    </select>
    Departamento:
    <select id="id_departamento" name="departamento">
        {%for departamento in departamentos%}
        <option value="{{departamento.slug}}">{{departamento.nombre}}</option>
        {%endfor%}
    </select>
    <input type="button" value="Filtrar" onClick="procesarFormulario(this.form)"/>
</form>
<div id="boton-grafo"><a href="#">Gráfico</a></div>
<div id="grafo"></div>
{{mensaje}}
<table>
    <tr>
        <th class="sortable-numeric">
            Año
        </th>
        {% if departamento %}
        <td>
          Departamento 
        </td>
        {% endif %}
        <th class="sortable-numeric">
          Enfermedades diarreicas agudas 
        </th>
        <th class="sortable-numeric">
          Enfermedades respiratorias agudas
        </th>
    </tr>
    {%for dato in datos%}
    <tr>
        <td class="{% cycle alt, none%}">
            {{dato.ano}}
        </td>
        {% if departamento %}
        <td class="{% cycle alt, none%}">
            <a href="/seguridad-alimentaria/utilizacion-biologica/{{dato.departamento.slug}}/">{{dato.departamento.nombre}}</a>
        </td>
        {% endif %}
        <td class="{% cycle alt, none%}">
            {{dato.enfermedades_diarreicas}}
        </td>
        <td class="{% cycle alt, none%}">
            {{dato.enfermedades_respiratorias}}
        </td>
    </tr>
    {%endfor%}
    <tfoot>
    <tr>
        {%if departamento%}
        <td colspan="2">
        {%else%}
        <td>
        {%endif%}
            Variaciones
        </td>
        <td>
            {{variaciones.variacion_eda|floatformat:2}}%
        </td>
        <td>
            {{variaciones.variacion_ira|floatformat:2}}%
        </td>
    </tr>
    </tfoot>
</table>
{% endblock %}